Added widgetastic.patternfly4
RedHatQE/taretto pull request #10
Opened 2018-10-08 06:51 UTC by quarckster

2018-10-30 14:04 UTC, RonnyPfannschmidt requested changes

2018-10-30 14:04 UTC, RonnyPfannschmidt commented on requirements.txt
> +widgetastic.patternfly~=0.1
there seems the `4` missing - also please rebase to master and remove the pin here, as we learned the unfortunate way that those pin can be impediments to downstream like cfme as the version resolver of pip is rather unfortunate

2022-02-09 15:47 UTC, mshriver approved these changes

2022-02-09 15:48 UTC, RonnyPfannschmidt approved these changes

2022-02-09 15:51 UTC, merged